name: vanashree
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  firebase_core: ^3.15.2
  flutter_svg: ^2.2.0
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  image_picker: ^1.1.2
  flutter_localization: ^0.3.3
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.0
  json_serializable: ^6.10.0
